# Problem 1

In [9]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.arange(0,10,2)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
print("-----------")
# 4 - matris'i yeniden boyutlandırın
b = a.reshape(5,1)
# 5 - matris'in boyut sayısını öğrenin
print(b.ndim)

(5,)
-----------
2


# Problem 2

In [19]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
x = np.array(np.arange(1,10,2))
# 2 - Oluşturduğunuz matrisi parçalayın
y,z = np.split(x,[1])
print(y)
print(z)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate((y,z)))

[1]
[3 5 7 9]
[1 3 5 7 9]


# Problem 3

In [51]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
w = np.random.choice((np.arange(5,100,2)),size = 10)
# 2 - matris'in özelliklerini inceleyin
w.argmax() #matrisin en büyük değerinin indeksi
print(w.reshape(2,5))
print(w.ndim)
print(w.size)
print(w.dtype)

[[17 75 73 15 17]
 [21 77 79 33 57]]
1
10
int32


In [33]:
print(w)

[97 17 73 11 47  7 25 21 21 59]
