# Problem 1 

In [16]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([8,5,95,62,8564,297])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(a))

[   5    8   62   95  297 8564]


# Problem 2

In [21]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print(sayilar)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2 = np.linspace(5,15)
print(sayilar2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayilar3 =np.arange(50,100,5)
print(sayilar3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilar4 = np.zeros(10)
print(sayilar4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar5 = np.ones(10)
print(sayilar5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayilar6 = np.linspace(0,100,5)
print(sayilar6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
sayilar7 = np.random.randint(10,31,size=5)
print(sayilar7)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
sayilar8 = np.random.uniform(-1,1,size=10)
print(sayilar8)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
sayilar9 = np.random.randint(10,50, size=(3,5))


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(sayilar9.sum(axis=0))
print(sayilar9.sum(axis=1))


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(sayilar9.max())
print(sayilar9.min())
print(sayilar9.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(sayilar9.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
sayilar10 = np.random.randint(10,20,size=8)
print(sayilar10[::3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(sayilar10[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(sayilar9[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(sayilar9[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(sayilar9[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(sayilar9**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
sayilar11 = np.random.uniform(-50,50, size = (3,5))
print(sayilar11[(sayilar11 % 2 == 0) & (sayilar11 > 0)])

[10 15 30 45 60]
[ 5.          5.20408163  5.40816327  5.6122449   5.81632653  6.02040816
  6.2244898   6.42857143  6.63265306  6.83673469  7.04081633  7.24489796
  7.44897959  7.65306122  7.85714286  8.06122449  8.26530612  8.46938776
  8.67346939  8.87755102  9.08163265  9.28571429  9.48979592  9.69387755
  9.89795918 10.10204082 10.30612245 10.51020408 10.71428571 10.91836735
 11.12244898 11.32653061 11.53061224 11.73469388 11.93877551 12.14285714
 12.34693878 12.55102041 12.75510204 12.95918367 13.16326531 13.36734694
 13.57142857 13.7755102  13.97959184 14.18367347 14.3877551  14.59183673
 14.79591837 15.        ]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 17 12 15 30]
[-0.68193598 -0.73480221  0.65904305  0.33585487 -0.60755697  0.49674625
 -0.94786177  0.93267231 -0.44445188  0.03549409]
[113  78 104  81 103]
[144 186 149]
47
16
31.933333333333334
9
[13 16 18]
[18 18 11 10 16 12 18 13]
[44 16 34 