# Numpy

* Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
* Veri analizinde kullanılır.
* Bilgisayar kurmak için pip inşall numpy komutu ile kurulabilir.
* Bilimsel hesaplamalar İçin kullanılır.
* Arraylar / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
* Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
* Listelere benzerdir, Fakat verimli veri şaklama ve vektör işlemleri İçin Numpy kullanılır,

In [1]:
pip install numpy

     -------------------------------------- 14.8/14.8 MB 189.9 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### Neden Numpy

In [2]:
# klasik yöntem

a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [3]:
# NUmöpy ile

import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a * b)

[ 2  6 12 20]


.reshape() fonksiyonu ile arraylerin boyutunu değiştirebiliriz

In [4]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arraylerin boyutunu öğrenebiliriz

In [5]:
print(multi.shape)

(3, 3)


.ndim ile arraylerin boyut sayısını öğrenebiliriz

In [6]:
print(multi.ndim)

2


In [7]:
print(x.ndim)

1


## Birleştirme (Concatenation)

. concantenate() fonksiyounu ile birleştirme yapabiliriz

In [8]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


- axis = 0 satır bazında birleştirme yapar
- axis = 1 sütun bazında birleştirme yapar

In [11]:
print(np.concatenate([a,a], axis=0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [12]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Array Ayrıma (Splitting)
.split() fonksiyonu ile array ayırma yapabilriz

In [13]:
m = np.array([1,2,3,4,55,55,2,1])
print(np.split(m, [3,5]))

[array([1, 2, 3]), array([ 4, 55]), array([55,  2,  1])]


In [14]:
a, b, c = np.split(m, [3,5])
print(a)
print(b)
print(c)

[1 2 3]
[ 4 55]
[55  2  1]


.vsplit() fonksiyonu ile array yatay olarak ayırma yapabilriz

In [16]:
n = np.arange(16).reshape(4,4)
np.vsplit(n, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

.hsplit() fonksiyonu ile array dikey olarak ayırma yapabilriz

In [17]:
np.hsplit(n, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

#### np.arange()

* belli bir aralıka sırayı oluşturmak için kullanılır
* np.arange(start, stop, step)

In [18]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

#### np.zeros()
* 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### np.ones()
* 1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır

In [21]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

#### np.linspace()
- belli bir aralıkta sayıları oluşturmak için kullanılır
- np.linspace(başlangıç, bitiş, bölünecek aralık)


In [23]:
np.linspace(4,24,6)

array([ 4.,  8., 12., 16., 20., 24.])

In [24]:
np.random.randint(0,10,3)

array([4, 2, 7])

In [26]:
np.random.randint(2,22,5)

array([ 6, 13,  2,  5, 16])

In [27]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis=1))

[ 45 145 245 345 445]


## Numpy Array'in Özellikleri
* ndim : boyut sayısı
* shape : boyut bilgisi
* size : toplam eleman sayısı
* dtype : veri tipi

In [28]:
a = np.random.randint(10, size = 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


## Array Sıralama(Sorting)
* array sıralama işlemlerini yaparken numpy kütüphanesinde yer alan "sort()" fonksiyonu kullanılır

In [33]:
v = np.array([8,24,32,15,55, 48])
print(v)
v.sort()
print(v)

[ 8 24 32 15 55 48]
[ 8 15 24 32 48 55]


In [35]:
m = np.random.normal(20,5,(3,3))
print(m)

[[17.53541629 22.30948047 15.66933731]
 [26.09686425 19.32314326 10.46119372]
 [24.71759951 21.81055817 22.44906744]]


In [39]:
print(np.sort(m, axis = 0))

[[17.53541629 19.32314326 10.46119372]
 [24.71759951 21.81055817 15.66933731]
 [26.09686425 22.30948047 22.44906744]]


In [38]:
print(np.sort(m, axis = 1))

[[15.66933731 17.53541629 22.30948047]
 [10.46119372 19.32314326 26.09686425]
 [21.81055817 22.44906744 24.71759951]]


## Index ile Elemanlara Erişmek
• Aynı listelerde olduğu gibi index ile elemanlara erişebiliriz.

In [40]:
a = np.random.randint(10, size = 10)
print(a[0])

8


In [41]:
a[0] = 5
print(a)

[5 7 5 5 4 3 0 1 3 3]


In [42]:
x = np.random.randint(10, size = (3,5))
print(x)

[[5 7 3 7 2]
 [0 9 1 2 0]
 [1 0 5 1 7]]


In [43]:
print(x[1,1])

9


In [45]:
x[1,4] = 100
print(x)

[[  5   7   3   7   2]
 [  0   9   1   2 100]
 [  1   0   5   1   7]]


In [47]:
x[1,4] = 11.6
print(x)

[[ 5  7  3  7  2]
 [ 0  9  1  2 11]
 [ 1  0  5  1  7]]


## Slicing ile Elemanlar Erişmek (Array Alt Kümesine Erişmek)

In [49]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [50]:
print(a[0:3])

[20 21 22]


In [51]:
print(a[:3])

[20 21 22]


In [52]:
print(a[3:])

[23 24 25 26 27 28 29]


In [53]:
print(a[1::2])

[21 23 25 27 29]


In [54]:
print(a[0::2])

[20 22 24 26 28]


In [56]:
print(a[2::3])

[22 25 28]


In [57]:
b = np.random.randint(10, size = [5,5])
print(b)

[[8 4 7 8 3]
 [1 0 8 6 8]
 [8 8 0 2 2]
 [2 8 6 6 0]
 [0 5 7 1 9]]


In [58]:
print(b[:,0])

[8 1 8 2 0]


In [59]:
print(b[:,1])

[4 0 8 8 5]


In [60]:
print(b[0,:])

[8 4 7 8 3]


In [61]:
print(b[1,:])

[1 0 8 6 8]


In [62]:
print(b[0:2,0:3])

[[8 4 7]
 [1 0 8]]


In [63]:
print(b[::2,::2])

[[8 7 3]
 [8 0 2]
 [0 7 9]]


## Alt Küme Üzerinde İşlem Yapmak

In [64]:
alt_b = b[0:3,0:2]
alt_b

array([[8, 4],
       [1, 0],
       [8, 8]])

In [66]:
alt_b[1,1] = 100
alt_b[2,1] = 200 
alt_b

array([[  8,   4],
       [  1, 100],
       [  8, 200]])

In [67]:
print(b)

[[  8   4   7   8   3]
 [  1 100   8   6   8]
 [  8 200   0   2   2]
 [  2   8   6   6   0]
 [  0   5   7   1   9]]


### Fancy Index
* bir liste içine bu arrayden istediğimiz indisleri koyarak o indislerdeki verileri alabiliriz

In [68]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [69]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [70]:
m = np.arange(9).reshape(3,3)
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir, sutun])

[1 5]


## KOşullu Eleman İşlemleri

In [71]:
v = np.array([1,2,3,4,5])
print(v > 3)

[False False False  True  True]


In [73]:
print(v [v > 3])

[4 5]


In [74]:
print(v [v <= 3])

[1 2 3]


In [75]:
print(v [v != 3])

[1 2 4 5]


In [76]:
print(v [v == 3])

[3]


## Matematiksel İşlemler

In [77]:
v = np.array([1,2,3,4,5])
print(v * 2)

[ 2  4  6  8 10]


In [78]:
print(v + 2)

[3 4 5 6 7]


In [79]:
print(v / 2.3)

[0.43478261 0.86956522 1.30434783 1.73913043 2.17391304]


In [80]:
print(np.subtract(v,3)) #  her birinden 3 çıkarıyor

[-2 -1  0  1  2]


In [81]:
print(np.add(v,4)) # toplama yapıyor

[5 6 7 8 9]


In [82]:
np.multiply(v,2) # çarpma işlemi

array([ 2,  4,  6,  8, 10])

In [83]:
np.divide(v,2) # bölme

array([0.5, 1. , 1.5, 2. , 2.5])

In [84]:
np.power(v,4) # üs alma

array([  1,  16,  81, 256, 625], dtype=int32)

In [85]:
np.mod(v,5) # mod alma

array([1, 2, 3, 4, 0], dtype=int32)

In [86]:
np.absolute(v) # mutlak değer

array([1, 2, 3, 4, 5])

In [87]:
np.sin(360)

0.9589157234143065

In [88]:
np.log(10)

2.302585092994046

In [89]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\AGU\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\agu\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are

## İki Bilinmeyenli Denklem Çözümü

In [92]:
# 5*x0 + x1 = 15
# x0 + 3*x1 = 18
a = np.array([[5,1], [1,3]])
b = np.array([15,18])
x = np.linalg.solve(a,b) # iki bilinmeyenli denklem çözümü
print(x)

[1.92857143 5.35714286]
